blank_issues_enabled: false
contact_links:
  - name: Ask Pyrogram related questions
    url: https://stackoverflow.com/questions/tagged/pyrogram
    about: This place is only for reporting issues about Pyrogram. You can ask questions at StackOverflow.
